---
name: Codeowners
on:
  [pull_request]
  # pull_request:
  # branches: ['master']
  # push:
  # branches: ['master']

jobs:
  codeowners:
    runs-on: [self-hosted, jammy]
    permissions:
      contents: read
      pull-requests: read
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 20

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v39

      - name: List all changed files
        run: |
          for file in ${{ steps.changed-files.outputs.all_modified_files }}; do
            echo "$file was changed"
            echo "pepe ${{ steps.changed-files.outputs.all_modified_files }}"
          done
          echo "pepe ${{ steps.changed-files.outputs.all_modified_files }}"

      - run: |
          echo ${{ steps.codeowners.outputs.codeowners }};

      - name: Install python
        uses: actions/setup-python@v4
        id: pinstall
        with:
          python-version-file: pyproject.toml

      - name: Install packages
        run: |
          pip install codeowners

      - name: Execute python
        run: |
          INPUT_STORE=${{ steps.changed-files.outputs.all_modified_files }} python nikita.py
  api:
    runs-on: ubuntu-latest
    steps:
      - run: |
          gh api \
            --method POST \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            /repos/nikita160/testActions/pulls/${PR_NUMBER}/requested_reviewers \
            -f "reviewers[]=de1n"
        env:
          GH_TOKEN: ${{ github.token }}
          PR_NUMBER: ${{ github.event.number }}
